export const EDITORIAL_TAGS = [
  "Surf-Town Classic",
  "Post-Surf Ritual",
  "Beach Road Staple",
  "Golden Hour Pick",
  "Sunset Energy",
  "Ocean-Adjacent",
  "Laptop-Friendly",
  "Long-Stay Favourite",
  "Basecamp Spot",
  "Remote-Work Approved",
  "Slow Mornings",
  "All-Day Anchor",
  "Easy Default",
  "Reliable Repeat",
  "Social Scene",
  "Group Dinner Pick",
  "Date Energy",
  "Solo Reset",
  "Light & Fresh",
  "Recovery Mode",
  "Reset Energy",
  "Plant-Forward",
  "Central Staple",
  "Tucked Away",
  "Off Main Strip",
  "Elevated Pick",
  "Signature Experience",
  "Community Hub",
  "Local Favourite",
] as const;

export type EditorialTag = (typeof EDITORIAL_TAGS)[number];
